/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import model.TaiKhoanNhanVien;
import model.TaiKhoanNhanVienDAO;

/**
 *
 * @author PhongVu
 */
public class FrDoiMatKhau extends javax.swing.JFrame {

    TaiKhoanNhanVienDAO dao = new TaiKhoanNhanVienDAO();

    /**
     * Creates new form FrDangNhap
     */
    public FrDoiMatKhau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_doiMatKhau = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_tenTaiKhoan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_matKhau = new javax.swing.JTextField();
        lb_dangKi = new javax.swing.JLabel();
        lb_dangNhap = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_xacNhanMatKhau = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đổi mật khẩu");
        jLabel1.setToolTipText("");

        btn_doiMatKhau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_doiMatKhau.setText("XÁC NHẬN");
        btn_doiMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_doiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doiMatKhauActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã nhân viên");

        txt_tenTaiKhoan.setForeground(new java.awt.Color(153, 153, 153));
        txt_tenTaiKhoan.setText("Nhập mã nhân viên...");
        txt_tenTaiKhoan.setToolTipText("");
        txt_tenTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_tenTaiKhoanMouseClicked(evt);
            }
        });
        txt_tenTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenTaiKhoanActionPerformed(evt);
            }
        });

        jLabel3.setText("Mật khẩu mới");

        txt_matKhau.setText("******");
        txt_matKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_matKhauMouseClicked(evt);
            }
        });
        txt_matKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matKhauActionPerformed(evt);
            }
        });

        lb_dangKi.setForeground(new java.awt.Color(0, 51, 204));
        lb_dangKi.setText("Chưa có tài khoản, đăng kí ở đây...");
        lb_dangKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_dangKiMouseClicked(evt);
            }
        });

        lb_dangNhap.setForeground(new java.awt.Color(0, 51, 204));
        lb_dangNhap.setText("Đăng nhập tại đây...");
        lb_dangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_dangNhapMouseClicked(evt);
            }
        });

        jLabel6.setText("Xác nhận");

        txt_xacNhanMatKhau.setText("******");
        txt_xacNhanMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_xacNhanMatKhauMouseClicked(evt);
            }
        });
        txt_xacNhanMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_xacNhanMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_dangKi)
                    .addComponent(lb_dangNhap)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_xacNhanMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_doiMatKhau)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_xacNhanMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_dangKi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_dangNhap)
                .addGap(18, 18, 18)
                .addComponent(btn_doiMatKhau)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tenTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenTaiKhoanActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txt_tenTaiKhoanActionPerformed

    private void txt_matKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matKhauActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_matKhauActionPerformed

    private void txt_xacNhanMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_xacNhanMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_xacNhanMatKhauActionPerformed

    private void txt_tenTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tenTaiKhoanMouseClicked
        // TODO add your handling code here:
        txt_tenTaiKhoan.setText("");
        txt_tenTaiKhoan.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_tenTaiKhoanMouseClicked

    private void txt_matKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_matKhauMouseClicked
        // TODO add your handling code here:
        txt_matKhau.setText("");
    }//GEN-LAST:event_txt_matKhauMouseClicked

    private void txt_xacNhanMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_xacNhanMatKhauMouseClicked
        // TODO add your handling code here:
        txt_xacNhanMatKhau.setText("");

    }//GEN-LAST:event_txt_xacNhanMatKhauMouseClicked

    private void lb_dangKiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_dangKiMouseClicked
        // TODO add your handling code here:
        FrDangKi frDangKi = new FrDangKi();
        frDangKi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_dangKiMouseClicked

    private void lb_dangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_dangNhapMouseClicked
        // TODO add your handling code here:
        FrDangNhap frDangNhap = new FrDangNhap();
        frDangNhap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_dangNhapMouseClicked
    public boolean validateForm() {
        if (txt_tenTaiKhoan.getText().isEmpty() || txt_matKhau.getText().isEmpty() || txt_xacNhanMatKhau.getText().isEmpty() || txt_tenTaiKhoan.getText().equals("Nhập mã nhân viên...") || txt_matKhau.getText().equals("******") || txt_xacNhanMatKhau.getText().equals("******")) {
            return false;
        }
        return true;
    }
    private void btn_doiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doiMatKhauActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            TaiKhoanNhanVien ee = new TaiKhoanNhanVien(txt_tenTaiKhoan.getText().trim(), txt_matKhau.getText());
            try {
                if (txt_matKhau.getText().equals(txt_xacNhanMatKhau.getText()) == false) {
                    JOptionPane.showMessageDialog(this, "Xác nhận không khớp!!!");
                } else {
                    if (dao.update(ee) > 0) {
                        JOptionPane.showMessageDialog(this, "Đổi thành công");
                        FrDangNhap frDangNhap = new FrDangNhap();
                        frDangNhap.setVisible(true);
                        this.setVisible(false);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đủ thông tin!!!");
        }
    }//GEN-LAST:event_btn_doiMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrDoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrDoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrDoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrDoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrDoiMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_doiMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lb_dangKi;
    private javax.swing.JLabel lb_dangNhap;
    private javax.swing.JTextField txt_matKhau;
    private javax.swing.JTextField txt_tenTaiKhoan;
    private javax.swing.JTextField txt_xacNhanMatKhau;
    // End of variables declaration//GEN-END:variables
}
