/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.DatabaseUtils;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.BanDia;
import model.BanDiaDAO;
import model.ChiTietBanDia;
import model.QuanLyKhoDia;
import model.QuanLyKhoDiaDAO;
import model.ThongTinNhanVien;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author PhongVu
 */
public class FrTrangChu extends javax.swing.JFrame {

    BanDiaDAO dao = new BanDiaDAO();
    QuanLyKhoDiaDAO daok = new QuanLyKhoDiaDAO();

    /**
     * Creates new form FrTrangChu
     */
    //Đổ dữ liệu vào jtable
    public void fillDatabase() {
        String[] arr = {"MaDia", "DonGia", "SoLuongMua", "GiamGia", "ThanhTien"};

        DefaultTableModel model = (DefaultTableModel) jTable_donHang.getModel();

        model.setRowCount(0);
        for (ChiTietBanDia ee : dao.getAllDonHang()) {
            if ((ee.getMaDonHang().trim()).equals(txt_maDonHang.getText())) {

                Object dataRow[] = new Object[5];
                dataRow[0] = ee.getMaDia();
                dataRow[1] = ee.getDonGia();
                dataRow[2] = ee.getSoLuongMua();
                dataRow[3] = ee.getGiamGia();
                dataRow[4] = ee.getThanhTien();
                model.addRow(dataRow);
            }

        }

    }

    //Add dữ liệu vào combobo
    public void fillCombobox() {
        for (ThongTinNhanVien ee : dao.LoadDataToCombobox()) {
            cb_maNhanVien.addItem(ee.getMaNV().toString());
        }
    }
    //Lấy giá trị hàng cuối cùng trong bảng HoaDonBan

    public void fillTextMaDonHang() {
        for (BanDia ee : dao.GiaTriHangCuoi()) {
            String cpChuoi = ee.getMaDonHang().substring(2).trim();
            int cpSo = Integer.valueOf(cpChuoi) +1 ;
            String maHD = "HD" + String.valueOf(cpSo);
            txt_maDonHang.setText(maHD);
        }
    }

    public void fillTongTien() {
        for (BanDia ee : dao.LoadDataToTongTien()) {
            if ((ee.getMaDonHang().trim()).equals(txt_maDonHang.getText())) {

                txt_tongTien.setText(String.valueOf(ee.getTongTien()));
            }
        }
    }

    public boolean kiemTraNhapSoLuongMua() {
        for (QuanLyKhoDia ee : daok.getAllDia()) {
            if ((ee.getMaDia().trim().equals(txt_maDia.getText().trim())) && (ee.getSoLuongCon() < Integer.valueOf(txt_soLuong.getText()))) {
                return false;
            }
        }
        return true;
    }

    public String laySoLuongDiaTrongKho() {
        for (QuanLyKhoDia ee : daok.getAllDia()) {
            if ((ee.getMaDia().trim().equals(txt_maDia.getText()))) {
                return String.valueOf(ee.getSoLuongCon());
            }
        }
        return "";
    }

    public FrTrangChu() {
        initComponents();
        fillTextMaDonHang();
        fillDatabase();
        fillTongTien();
        fillCombobox();

        //Dùng để chỉ chọn được một hàng duy nhất khi kích chuột vào jtable
        jTable_donHang.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        txt_timKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_donHang = new javax.swing.JTable();
        btn_timKiem = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_xoa = new javax.swing.JButton();
        btn_dong = new javax.swing.JButton();
        btn_nhapMoi = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_inHoaDon = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_maKhachHang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_thoiGian = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_tongTien = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_maDia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_donGia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_soLuong = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_giamGia = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        cb_maNhanVien = new javax.swing.JComboBox<>();
        txt_maDonHang = new javax.swing.JTextField();
        btn_luuThongTinChung = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_trangChu = new javax.swing.JMenu();
        jMenuTrangChu_thongTinCaNhan = new javax.swing.JMenuItem();
        jMenuTrangChu_doiMatKhau = new javax.swing.JMenuItem();
        jMenuTrangChu_Thoat = new javax.swing.JMenuItem();
        jMenu_quanLyKhoDia = new javax.swing.JMenu();
        jMenu_thongTinKhachHang = new javax.swing.JMenu();
        jMenu_doanhThu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        jMenu1.setText("jMenu1");

        jMenu7.setText("File");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar2.add(jMenu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_timKiem.setText("Nhập MaDia");
        txt_timKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_timKiemMouseClicked(evt);
            }
        });
        txt_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemActionPerformed(evt);
            }
        });

        jTable_donHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaDia","DonGia","SoLuongMua","GiamGia","ThanhTien"
            }
        )
        {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        jTable_donHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_donHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_donHang);

        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.setActionCommand("");
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.setActionCommand("");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN HÓA ĐƠN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setText("Tìm kiếm");

        btn_xoa.setText("Xóa");
        btn_xoa.setActionCommand("");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_dong.setText("Đóng");
        btn_dong.setActionCommand("");
        btn_dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dongActionPerformed(evt);
            }
        });

        btn_nhapMoi.setText("Nhập mới");
        btn_nhapMoi.setActionCommand("");
        btn_nhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhapMoiActionPerformed(evt);
            }
        });

        btn_them.setText("Thêm");
        btn_them.setActionCommand("");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_inHoaDon.setText("In Hóa Đơn");
        btn_inHoaDon.setActionCommand("");
        btn_inHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inHoaDonActionPerformed(evt);
            }
        });

        jLabel6.setText("Mã Đơn Hàng");

        jLabel7.setText("Mã Khách Hàng");

        jLabel8.setText("Mã Nhân Viên");

        jLabel10.setText("Thời Gian");

        txt_thoiGian.setEnabled(false);

        jLabel15.setText("Tổng tiền:");

        txt_tongTien.setText("0");
        txt_tongTien.setEnabled(false);

        jLabel16.setText("VNĐ");

        jLabel11.setText("Mã Đĩa");

        jLabel12.setText("Đơn Giá");

        jLabel13.setText("Số Lượng");

        jLabel14.setText("Giảm Giá");

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));

        txt_maDonHang.setEnabled(false);

        btn_luuThongTinChung.setText("Lưu");
        btn_luuThongTinChung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuThongTinChungActionPerformed(evt);
            }
        });

        jMenu_trangChu.setText("Trang Chủ");

        jMenuTrangChu_thongTinCaNhan.setText("Thông Tin Cá Nhân");
        jMenuTrangChu_thongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTrangChu_thongTinCaNhanActionPerformed(evt);
            }
        });
        jMenu_trangChu.add(jMenuTrangChu_thongTinCaNhan);

        jMenuTrangChu_doiMatKhau.setText("Đổi Mật Khẩu");
        jMenuTrangChu_doiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTrangChu_doiMatKhauActionPerformed(evt);
            }
        });
        jMenu_trangChu.add(jMenuTrangChu_doiMatKhau);

        jMenuTrangChu_Thoat.setText("Thoát");
        jMenuTrangChu_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTrangChu_ThoatActionPerformed(evt);
            }
        });
        jMenu_trangChu.add(jMenuTrangChu_Thoat);

        jMenuBar1.add(jMenu_trangChu);

        jMenu_quanLyKhoDia.setText("Quản Lý Kho Đĩa");
        jMenu_quanLyKhoDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_quanLyKhoDiaMouseClicked(evt);
            }
        });
        jMenu_quanLyKhoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_quanLyKhoDiaActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_quanLyKhoDia);

        jMenu_thongTinKhachHang.setText("Thông Tin Khách Hàng");
        jMenu_thongTinKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_thongTinKhachHangMouseClicked(evt);
            }
        });
        jMenu_thongTinKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_thongTinKhachHangActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_thongTinKhachHang);

        jMenu_doanhThu.setText("Doanh Thu");
        jMenu_doanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_doanhThuMouseClicked(evt);
            }
        });
        jMenu_doanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_doanhThuActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_doanhThu);

        jMenu2.setText("Hỗ Trợ");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_timKiem))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_thoiGian, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_maKhachHang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_maDia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_donGia)
                            .addComponent(txt_soLuong)
                            .addComponent(txt_giamGia)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_nhapMoi)
                                .addGap(18, 18, 18)
                                .addComponent(btn_them)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sua)
                                .addGap(18, 18, 18)
                                .addComponent(btn_xoa)
                                .addGap(18, 18, 18)
                                .addComponent(btn_inHoaDon)
                                .addGap(18, 18, 18)
                                .addComponent(btn_dong))
                            .addComponent(cb_maNhanVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_maDonHang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_luuThongTinChung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_maDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_maKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_maNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_thoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btn_luuThongTinChung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_maDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_donGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_giamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_nhapMoi)
                    .addComponent(btn_xoa)
                    .addComponent(btn_sua)
                    .addComponent(btn_dong)
                    .addComponent(btn_inHoaDon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validateForm() {
        if (txt_maDia.getText().isEmpty() || txt_donGia.getText().isEmpty() || txt_soLuong.getText().isEmpty() || txt_giamGia.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    public ChiTietBanDia getModel() {
        ChiTietBanDia ee = new ChiTietBanDia();
        ee.setMaDonHang(txt_maDonHang.getText());
        ee.setMaDia(txt_maDia.getText());
        ee.setDonGia(Integer.valueOf(txt_donGia.getText()));
        ee.setSoLuongMua(Integer.valueOf(txt_soLuong.getText()));
        ee.setGiamGia(Integer.valueOf(txt_giamGia.getText()));
        return ee;
    }

    private void resetForm() {
        txt_maDia.setText("");
        txt_donGia.setText("");
        txt_soLuong.setText("");
        txt_giamGia.setText("");
    }
    private void jMenuTrangChu_thongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTrangChu_thongTinCaNhanActionPerformed
        // TODO add your handling code here:
        FrThongTinNhanVien frThongTinNhanVien = new FrThongTinNhanVien();
        frThongTinNhanVien.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuTrangChu_thongTinCaNhanActionPerformed

    private void jMenuTrangChu_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTrangChu_ThoatActionPerformed
        // TODO add your handling code here:
        FrDangNhap frDangNhap = new FrDangNhap();
        frDangNhap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuTrangChu_ThoatActionPerformed

    private void jMenuTrangChu_doiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTrangChu_doiMatKhauActionPerformed
        // TODO add your handling code here:
        FrDoiMatKhau frDoiMatKhau = new FrDoiMatKhau();
        frDoiMatKhau.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jMenuTrangChu_doiMatKhauActionPerformed

    private void jMenu_quanLyKhoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_quanLyKhoDiaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu_quanLyKhoDiaActionPerformed

    private void jMenu_thongTinKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_thongTinKhachHangActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu_thongTinKhachHangActionPerformed

    private void jMenu_quanLyKhoDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_quanLyKhoDiaMouseClicked
        // TODO add your handling code here:
        FrQuanLyKhoDia frQuanLyKhoDia = new FrQuanLyKhoDia();
        frQuanLyKhoDia.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_jMenu_quanLyKhoDiaMouseClicked

    private void jMenu_thongTinKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_thongTinKhachHangMouseClicked
        // TODO add your handling code here:
        FrThongTinKhachHang frThongTinKhachHang = new FrThongTinKhachHang();
        frThongTinKhachHang.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu_thongTinKhachHangMouseClicked

    private void txt_timKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_timKiemMouseClicked
        // TODO add your handling code here:
        txt_timKiem.setText("");
    }//GEN-LAST:event_txt_timKiemMouseClicked

    private void txt_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemActionPerformed

    private void jTable_donHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_donHangMouseClicked
        // TODO add your handling code here:
        int i = jTable_donHang.getSelectedRow();
        TableModel model = jTable_donHang.getModel();
        txt_maDia.setText(model.getValueAt(i, 0).toString().trim());
        txt_donGia.setText(model.getValueAt(i, 1).toString());
        txt_soLuong.setText(model.getValueAt(i, 2).toString());
        txt_giamGia.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_jTable_donHangMouseClicked

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
        if (txt_timKiem.getText().isEmpty() || txt_timKiem.getText().equals("Nhập MaDia")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã Đĩa");
        } else {
            DefaultTableModel model = (DefaultTableModel) jTable_donHang.getModel();
            model.setRowCount(0);
            for (ChiTietBanDia ee : dao.getAllDonHang()) {
                if ((ee.getMaDonHang().trim()).equals(txt_maDonHang.getText()) && (ee.getMaDia().trim()).equals(txt_timKiem.getText())) {

                    Object dataRow[] = new Object[5];
                    dataRow[0] = ee.getMaDia();
                    dataRow[1] = ee.getDonGia();
                    dataRow[2] = ee.getSoLuongMua();
                    dataRow[3] = ee.getGiamGia();
                    dataRow[4] = ee.getThanhTien();
                    model.addRow(dataRow);

                }

            }
            txt_timKiem.setText("");
        }
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không?", "Thêm", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            if (validateForm()) {
                ChiTietBanDia eeNew = getModel();
                try {
                    
                    if (kiemTraNhapSoLuongMua() == false) {
                        JOptionPane.showMessageDialog(this, "Số lượng đĩa cần mua > " + laySoLuongDiaTrongKho() + " đĩa còn trong kho", "Lỗi Kho", JOptionPane.ERROR_MESSAGE);
                    } else {
                        if (kiemTraNhapSoLuongMua()==true&&dao.updateTTBan(eeNew) > 0) {
                            JOptionPane.showMessageDialog(this, "Sửa thành công");
                            fillDatabase();
                            fillTongTien();
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e.toString());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin!!!");
            }
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Thêm", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            if (txt_maDia.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập Mã Đĩa");
            } else {
                try {
                    if (txt_maDia.getText().isEmpty() == false) {
                        if (dao.deleteTTBan(txt_maDonHang.getText(), txt_maDia.getText()) > 0) {
                            JOptionPane.showMessageDialog(this, "Xóa thành công");
                            fillDatabase();
                            fillTongTien();
                        }
                    }

                    resetForm();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e.toString());
                }
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_dongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dongActionPerformed
        // TODO add your handling code here:
        FrDangNhap frDangNhap = new FrDangNhap();
        frDangNhap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_dongActionPerformed

    private void btn_nhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhapMoiActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btn_nhapMoiActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?", "Thêm", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            if (validateForm()) {
                ChiTietBanDia ee = getModel();
                try {
                    if (kiemTraNhapSoLuongMua() == false) {
                        JOptionPane.showMessageDialog(this, "Số lượng đĩa cần mua > " + laySoLuongDiaTrongKho() + " đĩa còn trong kho", "Lỗi Kho", JOptionPane.ERROR_MESSAGE);
                    } else {
                        if (kiemTraNhapSoLuongMua() == true && dao.addTTBan(ee) > 0) {
                            fillDatabase();
                            JOptionPane.showMessageDialog(this, "Thêm thành công");
                            resetForm();
                            fillTongTien();
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e.toString());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đủ thông tin!!!");
            }
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_inHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inHoaDonActionPerformed
        try {
            DatabaseUtils databaseUtils = new DatabaseUtils();
            databaseUtils.ReportHoaDon();
        } catch (SQLException ex) {
            Logger.getLogger(FrTrangChu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(FrTrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillTextMaDonHang();
        fillDatabase();
        txt_maKhachHang.setText("");
        txt_maDia.setText("");
        txt_donGia.setText("");
        txt_soLuong.setText("");
        txt_giamGia.setText("");
        btn_luuThongTinChung.setEnabled(true);
        txt_maKhachHang.setEnabled(true);
        cb_maNhanVien.setEnabled(true);

    }//GEN-LAST:event_btn_inHoaDonActionPerformed
    public boolean validateFormThongTinChung() {
        if (txt_maKhachHang.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    public BanDia getModelThongTinChung() {
        BanDia ee = new BanDia();
        ee.setMaDonHang(txt_maDonHang.getText());
        ee.setMaNV(cb_maNhanVien.getSelectedItem().toString());
        ee.setMaKH(txt_maKhachHang.getText());
        return ee;
    }
    private void btn_luuThongTinChungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuThongTinChungActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?", "Thêm", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            if (validateFormThongTinChung()) {
                BanDia ee = getModelThongTinChung();
                try {
                    if (dao.addTTChung(ee) > 0) {
                        fillDatabase();
                        JOptionPane.showMessageDialog(this, "Thêm thành công");
                        btn_luuThongTinChung.setEnabled(false);
                        txt_maKhachHang.setEnabled(false);
                        cb_maNhanVien.setEnabled(false);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e.toString());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đủ thông tin!!!");
            }
        }

    }//GEN-LAST:event_btn_luuThongTinChungActionPerformed

    private void jMenu_doanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_doanhThuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu_doanhThuActionPerformed

    private void jMenu_doanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_doanhThuMouseClicked
        // TODO add your handling code here:
        try {
            DatabaseUtils databaseUtils = new DatabaseUtils();
            databaseUtils.ReportTongDoanhThu();
        } catch (SQLException ex) {
            Logger.getLogger(FrTrangChu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(FrTrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu_doanhThuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrTrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dong;
    private javax.swing.JButton btn_inHoaDon;
    private javax.swing.JButton btn_luuThongTinChung;
    private javax.swing.JButton btn_nhapMoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cb_maNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuTrangChu_Thoat;
    private javax.swing.JMenuItem jMenuTrangChu_doiMatKhau;
    private javax.swing.JMenuItem jMenuTrangChu_thongTinCaNhan;
    private javax.swing.JMenu jMenu_doanhThu;
    private javax.swing.JMenu jMenu_quanLyKhoDia;
    private javax.swing.JMenu jMenu_thongTinKhachHang;
    private javax.swing.JMenu jMenu_trangChu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_donHang;
    private javax.swing.JTextField jTextField2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JTextField txt_donGia;
    private javax.swing.JTextField txt_giamGia;
    private javax.swing.JTextField txt_maDia;
    private javax.swing.JTextField txt_maDonHang;
    private javax.swing.JTextField txt_maKhachHang;
    private javax.swing.JTextField txt_soLuong;
    private javax.swing.JTextField txt_thoiGian;
    private javax.swing.JTextField txt_timKiem;
    private javax.swing.JTextField txt_tongTien;
    // End of variables declaration//GEN-END:variables
}
